Models/Jogador.cs
using System;
using System.Collections.Generic;
using System.IO;
using E_Players.Interfaces;

namespace E_Players.Models
{
    public class Jogador : EplayersBase, IJogador
    {
        public int IdJogador { get; set; }
        public string Nome { get; set; }
        public int IdEquipe { get; set; }

        private const string PATH = "Database/jogador.csv";
        /// <summary>
        /// Cria pasta e/ou arquivo
        /// </summary>
        public Jogador()
        {
            CreateFolderAndFile(PATH);
        }
        /// <summary>
        /// Cria uma linha na Database(csv)
        /// </summary>
        /// <param name="j"></param>
        public void Create(Jogador j)
        {
            string[] linha = { PrepararLinha(j) };
            File.AppendAllLines(PATH, linha);
        }
        /// <summary>
        /// Preparar linha na Database(csv)
        /// </summary>
        /// <param name="j"></param>
        /// <returns>retorna a forma padrão para a linha na Database(csv)</returns>
        private string PrepararLinha(Jogador j)
        {
            return $"{j.IdJogador};{j.Nome};{j.IdEquipe}";
        }
        /// <summary>
        /// Deletar uma linha da Database
        /// </summary>
        /// <param name="IdJogador"></param>
        public void Delete(int IdJogador)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == IdJogador.ToString());
            RewriteCSV(PATH,linhas);
        }
        /// <summary>
        /// Lê os dados da Database(csv)
        /// </summary>
        /// <returns>Retorna lista de jogadores</returns>
        public List<Jogador> ReadAll()
        {
            List<Jogador> jogadores = new List<Jogador>();
            string[] linhas = File.ReadAllLines(PATH);
            foreach (var item in linhas)
            {
                string[] linha = item.Split(";");
                Jogador jogador = new Jogador();
                jogador.IdJogador = Int32.Parse(linha[0]);
                jogador.Nome = linha[1];
                jogador.IdEquipe = Int32.Parse(linha[2]);
                jogadores.Add(jogador);
                
            }
            return jogadores;
        }
        /// <summary>
        /// Atualiza uma linha na Database(csv)
        /// </summary>
        /// <param name="j"></param>
        public void Update(Jogador j)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == IdJogador.ToString());
            linhas.Add(PrepararLinha(j));
            RewriteCSV(PATH,linhas);

        }
    }
}

Controllers/JogadorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using E_Players.Models;
using Microsoft.AspNetCore.Http;

namespace E_Players.Controllers
{
    public class JogadorController : Controller
    {
        Jogador jogadorModel = new Jogador();

        public IActionResult Index()
        {
            ViewBag.Jogadores = jogadorModel.ReadAll();
            return View();
        }    
        public IActionResult Cadastrar(IFormCollection form){
            Jogador novoJogador = new Jogador();
            novoJogador.IdJogador = Int32.Parse(form["IdJogador"]);
            novoJogador.Nome = form["Nome"];
            novoJogador.IdEquipe = Int32.Parse(form["IdEquipe"]);

            jogadorModel.Create(novoJogador);
            ViewBag.Jogadores = jogadorModel.ReadAll();
            return LocalRedirect("~/Jogador");
     
        }  
        [Route("[controller]/{id}")]
        public IActionResult Excluir(int id)
        {
            jogadorModel.Delete(id);
            ViewBag.Jogadores = jogadorModel.ReadAll();
            return LocalRedirect("~/Jogador");
        }
    }
}

Views/Jogador/Index.cshtml
@model Jogador
    @{
        ViewData["Title"] = "Jogadores";
    }

    <div class="titulo_pagina">
            <h1>cadastro de @ViewData["Title"]</h1>
    </div>

<form class="cadastro" method="POST" action='@Url.Action("Cadastrar")' enctype="multipart/form-data">

    <div class="campo">
        <label>ID Jogador</label>
        <input type="text" name="IdJogador" />
    </div>  

    <div class="campo">
        <label>Nome</label>
        <input type="text" name="Nome" />
    </div>

    <div class="campo">
        <label>ID Equipe</label>
        <input type="text" name="IdEquipe" />
    </div>

    <button class="gradient btn" type="submit">Cadastrar</button>

</form>

<table>
    <thead>
        <th>ID</th>
        <th>Nome</th>
        <th>Foto</th>
        <th>Ações</th>
    </thead>
    <tbody>
        @foreach(Jogador j in ViewBag.Jogadores){
            <tr>
                <td>@j.IdJogador</td>
                <td>@j.Nome</td>
                <td>@j.IdJogador</td>
                <td>
                    <a asp-area="" asp-controller="Jogador" asp-action="Excluir" asp-route-id="@j.IdJogador">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>